### ISSUE TITLE
Question: Import JSON format

### ISSUE THREAD

**Issue by abmusse** [tmo1/sms-ie#101]
Hello sms-ie community!

First off I would like Thank everyone who helped make this project happen!
I've been looking for a way to import and export message on Android!

I have some SMS messages in JSON format that was exported from an old iPhone using https://github.com/richinfante/iphonebackuptools. I would like to convert that JSON file into the proper fromat that can be used to import SMS messages using this tool. From the README I see that the export format is defined as documented in the Android API Reference: [SMS](https://developer.android.com/reference/android/provider/Telephony.TextBasedSmsColumns), [MMS](https://developer.android.com/reference/android/provider/Telephony.BaseMmsColumns).

If I convert my current JSON file to fo follow the SMS and MMS formats from the Android API, Will this be an acceptable import file for this sms-ie to accept?

**Comment by tmo1** [comment]
> If I convert my current JSON file to fo follow the SMS and MMS formats from the Android API, Will this be an acceptable import file for this sms-ie to accept?

Sure, as you long as you make sure of three things:

- The structure of the JSON must be [in the form that SMS I/E expects](https://github.com/tmo1/sms-ie#json-structure)
- The attribute names must be the ones used by Android internally
- The values must be in the form expected by Android (e.g., `date` must be in milliseconds since the epoch)

**Comment by tmo1** [comment]
The latter, please. There's an ongoing discussion about the JSON format SMS I/E uses [here](https://github.com/tmo1/sms-ie/discussions/55).
