### ISSUE TITLE
Allow_voicemails?

### ISSUE THREAD

**Issue by Biscorn** [tmo1/sms-ie#110]
Hi ! 

I am using this beautiful app to make few backups ! But I got a problem where it says, "Please set 'allow_voicemails=true' in the URI.

I am not sure how to do it nor handle it with an Android.

Nevertheless, I tried few things in my browser like that : content://call_log/calls?allow_voicemails=true, but the error continue.

I also opened the XML file through VS to check if a option was there, but nothing too.

What could be the solutions and how could I fix it ?

Thanks 💯

**Comment by tmo1** [comment]
Thank you!

This is an internal Android error. It's not something you can or should address - it seems to indicate that the app needs an adjustment in order to be able to properly access voice mail entries in the call logs:

* https://github.com/aosp-mirror/platform_packages_providers_contactsprovider/blob/master/src/com/android/providers/contacts/CallLogProvider.java

* https://android.googlesource.com/platform/packages/providers/ContactsProvider/+/92d9707%5E!/

* https://cs.android.com/android/platform/superproject/+/master:packages/providers/ContactsProvider/src/com/android/providers/contacts/CallLogProvider.java

See also:

* https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/provider/CallLog.java

I've never seen this error before, though. Please [post a logcat](https://github.com/tmo1/sms-ie#crashes), and please report exactly what version of Android you're running (and whether it's vanilla Android, or some sort of variant).

**Comment by tiberious726** [comment]
I'm running into the same error message. I've attached a logcat . I'm running GrapheneOS build TQ2A.230505.002.2023060700

[sms-io-logcat.txt](https://github.com/tmo1/sms-ie/files/11762112/sms-io-logcat.txt)

**Comment by tmo1** [comment]
> I'm running into the same error message. I've attached a logcat . I'm running GrapheneOS build TQ2A.230505.002.2023060700

Thank you - I will look into this when I get a chance.

**Comment by tmo1** [comment]
> I'm running into the same error message.

Where is the "Please set 'allow_voicemails=true' in the URI." message appearing? I don't see it in the logcat. If it's some kind of pop-up message, can you post a screenshot?

**Comment by lividhen** [comment]
Screenshot and logcat

![Screenshot_20230809_034017_SMS Import  Export](https://github.com/tmo1/sms-ie/assets/42221797/eb6ee917-f318-4594-9ef3-ba4ef404339e)
[logcat.zip](https://github.com/tmo1/sms-ie/files/12300740/logcat.zip)

**Comment by tmo1** [comment]
It turns out that this is a trickier and more frustrating - and poorly documented - problem than I first thought:

- Accessing voicemail requires the use of a special URI / query parameter, as per [here](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/provider/CallLog.java#781), [here](https://github.com/aosp-mirror/platform_packages_providers_contactsprovider/blob/master/src/com/android/providers/contacts/CallLogProvider.java#L1036) and [here](https://developer.android.com/reference/android/provider/CallLog.Calls#CONTENT_URI), but:
- [Using this URI requires](https://developer.android.com/reference/android/provider/CallLog.Calls#CONTENT_URI) "READ_VOICEMAIL and WRITE_VOICEMAIL permissions to read and write voicemails," however:
- The voicemail permissions are [only](https://stackoverflow.com/questions/75417504/is-there-anyway-to-grant-my-app-the-read-voicemail-permission-on-a-rooted-phone) [available](https://stackoverflow.com/questions/73291117/permissions-that-can-only-be-set-for-privilegged-apps) to privileged / system apps, and there's no clean way to grant them to ordinary apps.

It seems, then, that the best we can do is to try to exclude voicemail entries from call log import. I'm attaching [a build that does this](https://github.com/tmo1/sms-ie/files/12338397/sms_ie-skip-voicemail.zip) - please test and report your results.

**Comment by lividhen** [comment]
Skipping voicemail seems to work just fine.

**Comment by tmo1** [comment]
> Skipping voicemail seems to work just fine.

Thanks! If no one reports the problem persisting with the fix I posted within the next day or two, I'll commit it and close this issue.

**Comment by lividhen** [comment]
Awesome!
