### ISSUE TITLE
[BUG] Cannot set this app as the default messaging app.

### ISSUE THREAD

**Issue by CodeCubeNeo** [tmo1/sms-ie#124]
Hi!
I can't set this app as the default messaging app on my huawei p10 lite device running android 8. Ig it does not get recognised as a messaging app. Also why is there no confirmation to change the default messaging app from the app itself like with simple mobile tool's sms messenger or qksms? Thanks for feedback

**Comment by tmo1** [comment]
> I can't set this app as the default messaging app on my huawei p10 lite device running android 8. Ig it does not get recognised as a messaging app.

I've never seen this before. The app follows [the rules to be eligible to become the default SMS app](https://developer.android.com/reference/android/provider/Telephony#creating-an-sms-app), and it is able to become the default SMS app on all my devices and apparently on those of other users of the app as well.

What version of the app, and what exact version of Android, are you running?

> Also why is there no confirmation to change the default messaging app from the app itself like with simple mobile tool's sms messenger or qksms?

[This has been requested before](https://github.com/tmo1/sms-ie/issues/91#issuecomment-1646895657); I've never bothered implementing this because it didn't seem that necessary, but I'll consider doing so in the future.

**Comment by CodeCubeNeo** [comment]
Android version is 8.0.0 and I am using the latest version of the app - meaning 2.1.0. Idk, i restarted the phone, deleted some other apps, tried older versions of your app and it still does not get recognised on my huawei? Again some other open source messengers like qksms and simple sms messenger (https://github.com/SimpleMobileTools/Simple-SMS-Messenger) work fine (but they do ask for changing the default messaging app upon launch). Maybe you can check out how they implemented it?

**Comment by tmo1** [comment]
Hi,

The latest commit implements asking to become the default SMS app upon importing or wiping messages. I haven't made a release with this code yet, but please test it and see if it solves your problem. (You can either build the latest code yourself, or download an automatically built version as per [the Installation instructions](https://github.com/tmo1/sms-ie#installation).)

**Comment by CodeCubeNeo** [comment]
Yes, now it works and i can change it from the app (to import messages). ig it has to ask in order to appear in the list of default messaging apps. Thanks, please publish the release when you can. Awesome work!

**Comment by tmo1** [comment]
Thank you! I'll hopefully get the next release out within the next week or two.

**Comment by tmo1** [comment]
I just published the new release.
