### ISSUE TITLE
MMS not imported/exported correctly

### ISSUE THREAD

**Issue by Throun** [tmo1/sms-ie#79]
When importing my messages on an old phone, none of the MMS imported appear correctly. The SMS apps I tested show that a message exists, from the correct contact and sent or received at the correct time. However, the message itself does not appear. 

The app does show that MMS is being backed up when exporting and importing. Regular SMS messages from the same backups don't seem to be affected.
![Screenshot_20221201-213346](https://user-images.githubusercontent.com/112528632/205203620-cf133d9b-e0f4-4fda-a018-56570c59d2f3.png)

**Comment by tmo1** [comment]
- Did you by any chance turn off "Include (encoded) binary MMS data ..." when exporting?
- Inspect the JSON - do you see the missing message data there?
- What versions of SMS I/E and Android were used when exporting and importing?

**Comment by tmo1** [comment]
Okay - I've never seen or heard of something like this. Would you please post some JSON that demonstrates the problem, as per the guidelines [here](https://github.com/tmo1/sms-ie#posting-json)?

**Comment by tmo1** [comment]
Thank you. I'm working on this - I'll report any progress.

**Comment by tmo1** [comment]
The problem was the presence of tags named `sef_type` in the MMS parts. These are not present in the Android [`Telephony.MMS.Part`](https://developer.android.com/reference/android/provider/Telephony.Mms.Part) table, and they therefore caused the part inserts to fail. I have no idea what these tags are - perhaps they were introduced by one of the messaging apps ([QKSMS](https://github.com/moezbhatti/qksms) or [Simple Mobile Tools: Simple SMS Messenger](https://github.com/SimpleMobileTools/Simple-SMS-Messenger)) used on the source system?

In any event, the solution was to add a routine to drop all tags not present in the destination MMS part table ([something we previously had to do for the basic SMS and MMS tables](https://github.com/tmo1/sms-ie/issues/11)).

**Comment by tmo1** [comment]
Done.
